# Generated by Django 4.2.8 on 2023-12-11 01:58

import colorfield.fields
import datetime
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ("store", "0005_alter_product_name"),
    ]

    operations = [
        migrations.AlterField(
            model_name="siteconfig",
            name="color_action",
            field=colorfield.fields.ColorField(
                default="#00AFAF",
                help_text="Fill for buttons",
                image_field=None,
                max_length=25,
                samples=None,
            ),
        ),
        migrations.AlterField(
            model_name="siteconfig",
            name="color_action_text",
            field=colorfield.fields.ColorField(
                default="#000000",
                help_text="Text for buttons",
                image_field=None,
                max_length=25,
                samples=None,
            ),
        ),
        migrations.AlterField(
            model_name="siteconfig",
            name="color_primary",
            field=colorfield.fields.ColorField(
                default="#C200C2",
                help_text="For the site banner gradient",
                image_field=None,
                max_length=25,
                samples=None,
            ),
        ),
        migrations.AlterField(
            model_name="siteconfig",
            name="color_secondary",
            field=colorfield.fields.ColorField(
                default="#BE0000",
                help_text="For headings",
                image_field=None,
                max_length=25,
                samples=None,
            ),
        ),
        migrations.AlterField(
            model_name="siteconfig",
            name="site_name_color",
            field=colorfield.fields.ColorField(
                default="#0D8645", image_field=None, max_length=25, samples=None
            ),
        ),
        migrations.CreateModel(
            name="GiftCard",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("card_code", models.CharField(max_length=20, unique=True)),
                ("is_active", models.BooleanField(default=True)),
                (
                    "expiration_date",
                    models.DateField(default=datetime.date(2024, 12, 10)),
                ),
                (
                    "product",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="giftcards",
                        to="store.product",
                    ),
                ),
            ],
            options={
                "verbose_name_plural": "GiftCards",
            },
        ),
    ]
