# Generated by Django 4.2.8 on 2023-12-11 03:34

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("store", "0006_alter_siteconfig_color_action_and_more"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="product",
            name="inventory_count",
        ),
    ]
